[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "s3_client"
version = "0.1.1"
requires-python = ">=3.9"
dependencies = ["boto3"]

[tool.setuptools]
py-modules = ["s3_client"]
